### ISSUE TITLE
Unexpected token export when testing with jest.

### ISSUE THREAD

**Issue by adam-horvath** [shukerullah/react-geocode#10]
I use this library with React 15.6.2 and want to test my code with jest 22.2.1. When I run the tests, I get the following error:

export default {
^^^^^^
SyntaxError: Unexpected token export

**Comment by shukerullah** [comment]
I have updated module, can you please update to `v0.0.8` and verify it? Thanks.

**Comment by adam-horvath** [comment]
Thanks, it works now with v0.0.9!
