### ISSUE TITLE
Get all components of address

### ISSUE THREAD

**Issue by anasyo10** [shukerullah/react-geocode#17]
Is there any way to get all components of address from latlng:
- City,
- State,
- Postal code
- Address
Also Is there a way to get latlng from zipcode?

**Comment by douglasrcjames** [comment]
Bump

**Comment by jsib0** [comment]
@anasyo10 you are able to do this by parsing the response.results. As the module uses [Google Maps Geocoding API](https://developers.google.com/maps/documentation/geocoding/intro?#reverse-example), you are able to parse through your listed params. Hope this helps.
