### ISSUE TITLE
fromAddress only returns one result

### ISSUE THREAD

**Issue by ChrisLowe-Takor** [shukerullah/react-geocode#18]
```
Geocode.fromAddress(keyword).then(
    response => {
        console.log(response.count);
    },
    error => {
        window.console.log('error');
    }
);
```

Irregardless of what I enter the response only contains a single response.  Is there any way to get the full list of responses from the geocoder?

**Comment by naiveai** [comment]
I think this is actually just Google Maps being generally reliable in returning one result. Try using some more ambiguous addresses, I think you'll see how Google returns multiple results only when it's necessary.
