### ISSUE TITLE
What's this Project Got to do with React?

### ISSUE THREAD

**Issue by dhurlburtusa** [shukerullah/react-geocode#19]
Why is this project named `react-geocode`? It has nothing to do with React. It is an NPM wrapper for the Google Geocode API.

Would you unpublish the `react-geocode` NPM package and re-publish under a different name?

**Comment by shukerullah** [comment]
You are right, it has nothing to do with `React`, its just a name and I will not unpublish and re-publish with different name.

**Comment by GonzaloRizzo** [comment]
Very miss-leading name tho...
