### ISSUE TITLE
fromAddress doesn't work if address contains some special characters

### ISSUE THREAD

**Issue by alexandrugheorghiu** [shukerullah/react-geocode#20]
For an address that contains the special characters that the `encodeURI()` doesn't encode (i.e., , / ? : @ & = + $ #), e.g., _21 146TH AVE SE #3, BELLEVUE, WA 98007_, the `fromAddress()` doesn't return any results.

Possible fix: replace `encodeURI()` with `encodeURIComponent()`.

**Comment by shukerullah** [comment]
It's fixes now, thank you.
