### ISSUE TITLE
setLanguage is not a function

### ISSUE THREAD

**Issue by MouadBH** [shukerullah/react-geocode#23]
I got this error when I try to change language by using` Geocode.setLanguage()`
`Uncaught TypeError: react_geocode__WEBPACK_IMPORTED_MODULE_2___default.a.setLanguage is not a function`

**Comment by iamnubs** [comment]
same here...

**Comment by ghuniyu** [comment]
> I got this error when I try to change language by using` Geocode.setLanguage()`
> `Uncaught TypeError: react_geocode__WEBPACK_IMPORTED_MODULE_2___default.a.setLanguage is not a function`

same here...

**Comment by Muttakee31** [comment]
facing the same problem. Has anybody found a solution?

**Comment by homerteo** [comment]
I have this same problem, but seeing the documentation in the module Readme in version 0.1.2 this function does not appear. Has it been removed from the package?

**Comment by shukerullah** [comment]
Updated.
