### ISSUE TITLE
Install issue: Can't Resolve 'regenerator-runtime'

### ISSUE THREAD

**Issue by sselfridge** [shukerullah/react-geocode#26]
trying to use the package and after installing it and placing the require statement in my project I get the following error when running my project

client:159 ./node_modules/react-geocode/lib/index.js
Module not found: Error: Can't resolve 'regenerator-runtime' in '{DIR}/node_modules/react-geocode/lib'

Manually installing regenerator-runtime compiles without error

**Comment by shukerullah** [comment]
Hi, can you try latest version please?

**Comment by shukerullah** [comment]
Hi, can you try latest version please?

**Comment by sselfridge** [comment]
Working now with "^0.2.0"
