### ISSUE TITLE
[Question] Can I get Address from Zipcode?

### ISSUE THREAD

**Issue by fzs1994** [shukerullah/react-geocode#27]

**Comment by shukerullah** [comment]
Here is an example to get address form zip code 

```
Geocode.fromAddress('01210,PL').then(
  response => {
    ...
  },
  error => {
    ...
  },
);
```

**Just a hint**: zip codes are not worldwide unique so this is worth to provide country ISO code in the request [https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)

[Credits](https://stackoverflow.com/a/46935793/5315786)
