### ISSUE TITLE
InvalidKeyMapError

### ISSUE THREAD

**Issue by paddibr** [shukerullah/react-geocode#37]
Hey, since some days i get these error from react-geocode:

Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error

But i didn't change anything. Does someone know the problem?

**Comment by ziyaddin** [comment]
Official description of the error:

> The API key included in the script element that loads the API is not found. Please make sure you are using a correct API key. You can generate a new API key in the Google Cloud Platform Console. 

I think your Google Maps API Key is not correct. It is either deleted or not valid anymore.

**Comment by ziyaddin** [comment]
@paddibr any success?

**Comment by paddibr** [comment]
yes, I wrote to Google. Problem was the copyrights inside the suggets window. So google is blocking domains if not.

**Comment by ziyaddin** [comment]
Okay then. As no issues left, I am closing it.
