### ISSUE TITLE
Uncaught TypeError: react_geocode__WEBPACK_IMPORTED_MODULE_2___default.a.setRegion is not a function

### ISSUE THREAD

**Issue by SaiShangAI** [shukerullah/react-geocode#39]

**Comment by SaiShangAI** [comment]
hi @shukerullah  I got the error when I want to ser my region. Could you help me with the issue? Many thanks

**Comment by ziyaddin** [comment]
Hi @SaiShangAI, could you paste here your code where you **import** the library and **use** `setRegion` function?

**Comment by SaiShangAI** [comment]
hi @ziyaddin I import the library and would like to set the region in a file like this:
```js
import React from 'react';
import {
  GoogleMap,
  InfoWindow,
  KmlLayer,
  Marker,
  withGoogleMap,
  withScriptjs
} from 'react-google-maps';
import Geocode from 'react-geocode';
import * as PropTypes from 'prop-types';

Geocode.enableDebug();
Geocode.setRegion('cn')
Geocode.setApiKey('XXXXXXXXXXXXXX');
......
```

**Comment by SaiShangAI** [comment]
<img width="651" alt="Screen Shot 2020-11-04 at 10 59 58 AM" src="https://user-images.githubusercontent.com/47818273/98097146-e3246500-1e8c-11eb-8924-84f9c3ff9c53.png">
hi @ziyaddin  it seems like the function `setRegion` is not defined

**Comment by SaiShangAI** [comment]
hi @ziyaddin  I use typescript

**Comment by ziyaddin** [comment]
@SaiShangAI could you install [@types/react-geocode](https://www.npmjs.com/package/@types/react-geocode) package and see if it works after that?

**Comment by SaiShangAI** [comment]
hi @ziyaddin  nope, doesn't work

**Comment by SaiShangAI** [comment]
<img width="882" alt="Screen Shot 2020-11-04 at 11 19 30 AM" src="https://user-images.githubusercontent.com/47818273/98099259-9ee69400-1e8f-11eb-9b85-d7e0866e2ebc.png">

**Comment by ziyaddin** [comment]
> <img alt="Screen Shot 2020-11-04 at 10 59 58 AM" width="651" src="https://user-images.githubusercontent.com/47818273/98097146-e3246500-1e8c-11eb-8924-84f9c3ff9c53.png">

@SaiShangAI where is this type file located? Can you remove it?

**Comment by ziyaddin** [comment]
@SaiShangAI the type, you are using, is wrong. The correct one is [@types/react-geocode](https://www.npmjs.com/package/@types/react-geocode). You should somehow remove the wrong one.

**Comment by SaiShangAI** [comment]
hi @ziyaddin I removed the react-geocode and install @types/react-geocode. But When I import ` import Geocode from '@types/react-geocode'`, the terminal show Module is not found. So I would like to ask If my importing is right? many thanks

**Module not found: Can't resolve '@types/react-geocode'**

**Comment by SaiShangAI** [comment]
<img width="590" alt="Screen Shot 2020-11-04 at 12 08 13 PM" src="https://user-images.githubusercontent.com/47818273/98104203-6ac2a180-1e96-11eb-8c01-eee00e3c5412.png">

**Comment by ziyaddin** [comment]
@SaiShangAI you should import Geocode not from `@types/react-geocode` but `react-geocode`:

```js
import Geocode from 'react-geocode';
```

`@types/react-geocode` will help you with types by suggesting them to you. No need to import this package into your code.

Please, try and inform me if it works.

**Comment by SaiShangAI** [comment]
hi @ziyaddin  I installed `@types/react-geocode` and `react-geocode`. But still  I don't know how to make **Geocode** link to the right types.

**Comment by ziyaddin** [comment]
@SaiShangAI where is the old type file, you showed me via image above, located? By default, each library tries to link to its own `@types/bla-bla-bla` package.

**Comment by SaiShangAI** [comment]
hi @ziyaddin  the **Type definitions for react-geocode 0.2**. I installed the version is 0.1.2. Now I use the newest react-geocode version. It works. Many thanks🙏 for your help. Really appreciate.

**Comment by ziyaddin** [comment]
@SaiShangAI you're welcome.
