### ISSUE TITLE
How to set India as region?

### ISSUE THREAD

**Issue by sumit151199** [shukerullah/react-geocode#40]
How to set India region ?
using these but didn't work
  Geocode.setRegion("ind");
  Geocode.setRegion("IND");
  Geocode.setRegion("INDIA");

**Comment by ziyaddin** [comment]
Take a look at this docs:
https://developers.google.com/maps/documentation/javascript/geocoding#GeocodingRequests
> region — The region code, specified as a IANA language region subtag. In most cases, these tags map directly to familiar ccTLD ("top-level domain") two-character values. The region parameter will only influence, not fully restrict, results from the geocoder. See more information about region code biasing below.

IANA subtag for India is "IN". Refer to this document: http://www.iana.org/assignments/language-subtag-registry

**Comment by ziyaddin** [comment]
@sumit151199 have you solved the issue?
