### ISSUE TITLE
outputFormat required in setDefaults

### ISSUE THREAD

**Issue by jonathan-chin** [shukerullah/react-geocode#50]
I tried to use `setDefaults` as it is shown in the README by specifying only `key`, `language`, and `region`.

however, my typescript compiler complained that `outputFormat` was required. not a big deal but might be confusing for anyone who wants to quickly try the package and is just following the README.

**Comment by MarkoMalec** [comment]
I really want to get rid of this error and I have no idea how

**Comment by Devdannnny** [comment]
> You can use this:

import { OutputFormat } from "react-geocode";

setDefaults({
        key: "", // Your API key here.
        language: "en", // Default language for responses.
        region: "gh", // Default region for responses.
        outputFormat:OutputFormat.JSON
      });

**Comment by jonathan-chin** [comment]
I guess my issue was that the sample code in the README would not compile. I'd suggest updating it to include the required parameters.
