### ISSUE TITLE
Why it's called `react-geocode` if it works everywhere?

### ISSUE THREAD

**Issue by AbdUlHamedMaree** [shukerullah/react-geocode#51]
normally react packages should have either Components, hooks, or anything related to react, but this one doesn't.
is there a plan to have something in the future?

**Comment by shukerullah** [comment]
Hi @AbdUlHamedMaree, you're right, react-geocode works everywhere, not just React. We originally built it for React but expanded its use. We've clarified this in the README.

**Comment by AbdUlHamedMaree** [comment]
@shukerullah we can maybe add some useful hooks and then, it would be more useful for developers.
I can contribute if you think it's a good idea
