### ISSUE TITLE
Fails to minify

### ISSUE THREAD

**Issue by huangjoyce3** [shukerullah/react-geocode#9]
I was getting this error when I ran `npm run build` on my project. Let me know if I can provide more information. https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify
![image](https://user-images.githubusercontent.com/17226026/38177356-e74416f8-35b4-11e8-8243-94608a8c4b19.png)

**Comment by JTDeLeon** [comment]
Hello, I am having the same issue as [@huangjoyce3]. 

Based on the docs that are linked here it references using ES5 code, I tried reverting the version of react-geocode to version 0.0.3 and I am still having a minify issue, but it references a different line of code (index.js 29)

<img width="349" alt="screen shot 2018-04-05 at 11 17 11 am" src="https://user-images.githubusercontent.com/23343360/38374941-f7793718-38c2-11e8-9ff7-2dc606e48e3c.png">

My issue still persists and look forward to receiving feedback on helping resolve this <code>npm run build</code> minify issue.

**Comment by shukerullah** [comment]
Updated module.
